baseURL = 'https://j404.dev'
languageCode = 'en-us'
title = 'j404.dev'
theme = "j404_theme"

[menus]
  [[menus.main]]
    name = "blog"
    pageRef = "/posts"
    weight = 1
  [[menus.main]]
    name = "about"
    pageRef = "/about"
    weight = 2
